name: NFC Log

on:
  workflow_dispatch:

permissions:
  contents: write   # ←← これが必須！！

jobs:
  append_log:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Python script
        run: |
          python3 log_script.py

      - name: Commit changes
        run: |
          git config user.name "NFC Logger Bot"
          git config user.email "bot@example.com"
          git add nfc_log.csv
          git commit -m "Add log"
          git push
